name: Features
on:
  pull_request:
    types: [
      synchronize, # PR was updated
      opened, # PR was open
    ]
      
jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Test Action
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: ebeagusamuel
          repo: newsweek-clone
          workflow_file_name: features.yml
          github_token: ${{ secrets.PAT }}
          ref: ${{ github.sha }}
          wait_interval: 10
          propagate_failure: true
          wait_workflow: true
          inputs: '{
            "talent_portal_branch": "${{ github.sha }}",
            "platform_branch": "master",
            "billing_branch": "master"
            "job_name_prefix": "talent_portal",
            "testbox_profile": "talent_portal",
            "cucumber_profile": "jenkins_talent_portal_testbox",
            "worker_count": "12",
            "kubernetes_namespaces_basename": "talent-portal"
          }'
        
        